In [38]:
#DSTT ASSIGNMENT-2

#ATMAKURU RAGHUNANDAN
#24-27-33
#MTECH-DATA SCIENCE

In [39]:
#Q1

In [40]:
import numpy as np

# a) Create var1 with numbers from 0 to 30 (31 elements) and print its shape
var1 = np.arange(0, 31)  # 31 elements from 0 to 30
print("var1:\n", var1)
print("var1 shape:", var1.shape)

var1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var1 shape: (31,)


In [41]:
# b) Reshape var1_for_reshaping into a validly-shaped 2D matrix (6x5) and assign to var2
var1_for_reshaping = var1[:30]  # Use elements from 0 to 29

var2 = var1_for_reshaping.reshape(6, 5)
print("\nvar2:\n", var2)
print("var2 shape:", var2.shape)


var2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
var2 shape: (6, 5)


In [42]:
# c) Reshape var1_for_reshaping into a validly-shaped 3D matrix and assign to var3
var3 = var1_for_reshaping.reshape(2, 3, 5)
print("\nvar3:\n", var3)
print("var3 shape:", var3.shape)


var3:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
var3 shape: (2, 3, 5)


In [43]:
# d) Modify the first value in the second row of var2 to -1
var2[1, 0] = -1
print("\nModified var2:\n", var2)


Modified var2:
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [44]:
# Check if var1 and var3 changed after modifying var2
print("\nvar1 after modification:\n", var1)
print("var3 after modification:\n", var3)


var1 after modification:
 [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3 after modification:
 [[[ 0  1  2  3  4]
  [-1  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [45]:
#This behavior demonstrates that reshape() in NumPy creates a view (when possible), 
#so changes made in one reshaped version (like var2) can affect the original array (var1) and other reshaped versions (var3)

In [46]:
# e) Sum var3 over different dimensions
# (i) Sum over the second dimension (axis=1)
sum_var3_axis1 = np.sum(var3, axis=1)
print("\nSum of var3 over the second dimension (axis=1):\n", sum_var3_axis1)



Sum of var3 over the second dimension (axis=1):
 [[ 9 18 21 24 27]
 [60 63 66 69 72]]


In [47]:
# (ii) Sum over the third dimension (axis=2)
sum_var3_axis2 = np.sum(var3, axis=2)
print("\nSum of var3 over the third dimension (axis=2):\n", sum_var3_axis2)



Sum of var3 over the third dimension (axis=2):
 [[ 10  29  60]
 [ 85 110 135]]


In [48]:
# (iii) Sum over both the first and third dimensions (axis=(0,2))
sum_var3_axis0_2 = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over both the first and third dimensions (axis=(0,2)):\n", sum_var3_axis0_2)



Sum of var3 over both the first and third dimensions (axis=(0,2)):
 [ 95 139 195]


In [49]:
# f) Slicing operations on var2
# (i) Slice out the second row of var2
second_row_var2 = var2[1, :]
print("\nSecond row of var2:\n", second_row_var2)


Second row of var2:
 [-1  6  7  8  9]


In [50]:
# (ii) Slice out the last column of var2
last_column_var2 = var2[:, -1]
print("\nLast column of var2:\n", last_column_var2)



Last column of var2:
 [ 4  9 14 19 24 29]


In [51]:
# (iii) Slice out the top-right 2x2 submatrix of var2
top_right_2x2_var2 = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:\n", top_right_2x2_var2)



Top-right 2x2 submatrix of var2:
 [[3 4]
 [8 9]]


In [52]:
#Q2

In [53]:
import numpy as np

# a) Create a vector [1, 2, ..., 10]
vector = np.arange(10) + 1
print("Vector [1, 2, ..., 10]:\n", vector)

Vector [1, 2, ..., 10]:
 [ 1  2  3  4  5  6  7  8  9 10]


In [54]:
# b) Create a 10x10 matrix A where A_ij = i + j
A = vector.reshape(10, 1) + vector  # Broadcasting of column and row vectors
print("\n10x10 Matrix A (where A_ij = i + j):\n", A)


10x10 Matrix A (where A_ij = i + j):
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [55]:
# c) A very common use of broadcasting is to standardize data, i.e., to make it have
    #zero mean and unit variance. First, create a fake “data set” with 50 examples,
    #each with five dimensions.

In [56]:
import numpy as np
import numpy.random as npr

# Generate a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))
print("Original data:\n", data)

# Standardize the dataset (zero mean and unit variance)
# Calculate the mean and standard deviation along each column (feature)
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

# Standardize: (data - mean) / std_dev
standardized_data = (data - mean) / std_dev
print("\nStandardized data (zero mean, unit variance):\n", standardized_data)

# Check the mean and standard deviation after standardization
print("\nMean of standardized data:\n", np.mean(standardized_data, axis=0))
print("Standard deviation of standardized data:\n", np.std(standardized_data, axis=0))


Original data:
 [[ 3.33322183  2.16105675  1.6165294   2.44915588  0.95091106]
 [ 0.62350384  2.31139018 31.66680256  1.6616429   1.01939051]
 [ 1.69078544  0.63142514  4.54687133  0.36973856  2.20030633]
 [ 0.83455409  0.92115915  0.31852413  0.64041062  1.57702774]
 [ 1.2439824   0.28090362  4.80441242  0.48488945  1.32021148]
 [ 0.44621794  1.45600455  1.59095618  2.502187    0.38209587]
 [ 4.07766859  0.35919306  0.46519491  0.54185675  3.35872699]
 [ 2.02568086  0.58250506  0.52463478  0.13664462  3.54118307]
 [ 0.87929081  0.09180476  1.43494594  1.06435237  0.95338371]
 [ 1.20776118  5.52172949  1.39789089  0.33668488  0.15067155]
 [ 7.29413344  0.30888377  0.97835309  2.05095969  1.77856701]
 [ 0.35641422  1.66062485  0.84238379  0.28835846  0.87940882]
 [ 0.92290692  0.80960982  1.32378336  8.58175115  0.10196889]
 [ 0.94694598  0.59925692  1.26896121  1.73845515  0.89993659]
 [ 0.11924722  3.46284765  3.47191728  1.08185049  1.40130125]
 [ 0.6480572   1.50716632  0.35941095  

In [57]:
# e)
import numpy as np
import numpy.random as npr

# Generate a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation of each column
mean_vector = np.mean(data, axis=0)  # Mean along each column (axis=0)
std_vector = np.std(data, axis=0)    # Standard deviation along each column (axis=0)

# Print the mean and standard deviation vectors
print("Mean of each column:\n", mean_vector)
print("\nStandard deviation of each column:\n", std_vector)


Mean of each column:
 [1.95844214 1.1263572  1.15753004 1.6809504  2.3962808 ]

Standard deviation of each column:
 [2.00657338 1.09270544 1.36851322 1.69273114 4.38625501]


In [58]:
# f)
import numpy as np
import numpy.random as npr

# Generate a fake dataset with 50 examples and 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation of each column
mean_vector = np.mean(data, axis=0)  # Mean along each column (axis=0)
std_vector = np.std(data, axis=0)    # Standard deviation along each column (axis=0)

# Standardize the data: subtract the mean and divide by the standard deviation
normalized = (data - mean_vector) / std_vector

# Print the normalized data
print("Normalized data:\n", normalized)

# Verify the standardization by computing the mean and standard deviation of the normalized data
normalized_mean = np.mean(normalized, axis=0)  # Mean of normalized data
normalized_std = np.std(normalized, axis=0)    # Standard deviation of normalized data

# Print the mean and standard deviation of the normalized data
print("\nMean of normalized data (should be close to 0):\n", normalized_mean)
print("\nStandard deviation of normalized data (should be close to 1):\n", normalized_std)


Normalized data:
 [[ 0.12358632 -0.24581684  0.51919395 -0.67091492 -0.83175184]
 [-0.12196724 -0.80241101  0.41972854 -0.60567183 -0.61566565]
 [-0.59973115 -0.79250584  1.17501481  0.06124716 -0.46175385]
 [-0.36120935 -0.66405736 -0.1454348   0.8956966   4.44471592]
 [ 0.56834169 -0.70509457  0.38965219  2.89541642 -0.49697766]
 [-0.01563405  1.92255888  1.13961237 -0.59087816 -0.76821676]
 [ 0.90544951 -0.79587    -0.9080985  -0.70832072 -0.29398969]
 [-0.5772464  -0.77103873 -0.19339127 -0.53243899 -0.86090636]
 [ 2.68814944  0.12950289 -0.67118892  0.40690415 -0.20954879]
 [-0.57858962 -0.28724348 -0.43739669  0.68695349 -0.17304981]
 [ 0.55780816  0.6396713   3.01953906 -0.06406273  1.48695461]
 [-0.76824124  0.72300688 -0.2025527  -0.52693224 -0.33723112]
 [ 2.00560369 -0.80501839 -0.2911481  -0.31717163 -0.0556549 ]
 [-0.20025869  0.65133663  0.31524154 -0.57691824  0.08853778]
 [ 0.85877656 -0.78288319 -0.28317381 -0.05613381 -0.3342088 ]
 [ 0.35157182 -0.57910403 -0.31490164

In [59]:
# Q3
# a) A Vandermonde matrix
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = np.power(vec[:, np.newaxis], np.arange(N))
    
    return vander
vander = vandermonde(12)
print("Vandermonde matrix for N=12:\n", vander)


Vandermonde matrix for N=12:
 [[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
  

In [60]:
# b)
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = np.power(vec[:, np.newaxis], np.arange(N))
    return vander

# Create the Vandermonde matrix for N = 12
vander = vandermonde(12)

# Create a vector of ones with length 12
x = np.ones(12)

# Perform matrix-vector multiplication
b = np.dot(vander, x)

# Print the resulting vector b
print("Vector b (result of matrix-vector multiplication):\n", b)


Vector b (result of matrix-vector multiplication):
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [61]:
# c)
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = np.power(vec[:, np.newaxis], np.arange(N))
    
    return vander

vander = vandermonde(12)

x = np.ones(12)

# Perform matrix-vector multiplication
b = np.dot(vander, x)

# Import numpy's linear algebra module
import numpy.linalg as la

# Solve the linear system by inverting V and multiplying by b
x_recovered = la.inv(vander).dot(b)

# Print the result
print("Recovered x from the inverse of Vandermonde matrix:\n", x_recovered)


Recovered x from the inverse of Vandermonde matrix:
 [0.99620819 1.00462723 0.99909973 1.00006104 0.99999666 1.00000048
 0.99999995 1.         1.         1.         1.         1.        ]


In [62]:
# d)
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    vander = np.power(vec[:, np.newaxis], np.arange(N))
    
    return vander

vander = vandermonde(12)
x = np.ones(12)

# Perform matrix-vector multiplication
b = np.dot(vander, x)

# Solve the linear system using np.linalg.solve
x_solved = np.linalg.solve(vander, b)

# Print the result
print("Solved x using np.linalg.solve:\n", x_solved)


Solved x using np.linalg.solve:
 [0.99998827 1.00002951 0.99997139 1.00001427 0.99999595 1.00000068
 0.99999993 1.         1.         1.         1.         1.        ]
